### ISSUE TITLE
Mailchimp multiple subscription of the same user

### ISSUE THREAD

**Issue by volfkarlo** [infinum/eightshift-forms#121]
On the Academy project we had problems with previously subscribed users. The problem arose when a user is created and then the same one wants to subscribe once more, you get an error message saying that the user is already created, that's why you have to update the user with the new mailing list, tag, or something similar to it.
Reference:
Academy Project:
class-apply-form:
https://github.com/infinum/wordpress-infinum-web/blob/master/wp-content/themes/academy/src/blocks/custom/apply-form/class-apply-form.php

Lines: 672-698
and function on line 527 `update_contact_mailchimp`

**Comment by iruzevic** [comment]
Not sure that I understand 100%.

When the user exists you get the msg that it all-ready exists. I used the PUT option every time. So if the user exists it will update his/hers first/name,etc if it doesnt it will create a new user.

Is this correct?

Not sure about changing the mailing list? Why would you want to do that?

**Comment by volfkarlo** [comment]
> Is this correct?
Yep, it seems like you've covered that case by using a different endpoint(a much better one).

What I thought is that the endpoint that is used is https://mailchimp.com/developer/marketing/api/list-members/add-member-to-list/ which requires the POST method and causes problems.

I believe this is the correct and much better way.
Thanks for the info.

> Not sure about changing the mailing list? Why would you want to do that?
Situation A:
Let's say you have a mailing list called Newsletter subscribers that is being used for newsletter subscribers. Your list has different TAGS like _Development_, _Design_, _QA_.

A subscriber is added to a _Newsletter subscribers_ mailing list with _Development_ tag (because he subscribed to a newsletter on a development blog post or something similar).  But then the same subscriber wants to subscribe for _Design_ newsletter. 

Will the _Development_ tag be overwritten or will the _Design_ tag be added additionally to it?

Situation B:
Let's say you have a mailing list called _Newsletter subscribers_ that is being used for newsletter subscribers. Your list has different TAGS like _Development_, _Design_, _QA_ but this time you also have a mailing list named _Job Applicants_.

If a job applicant is firstly subscribed to a newsletter and then applied for the job. Will the lists for this user be correct?

I assume both situations are covered, I just wanted to assure that these are checked.


If both situations work, feel free to close the issue 😄 
Thanks for immediate comment.

**Comment by iruzevic** [comment]
I haven't tackled tags and segments in this initial version but I will make this work in the next version. Tnx for the detailed info, it is very useful
