### ISSUE TITLE
Add all icons

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-forms#145]
# Attributes:
- [x] field type
- [x] data to show
- [x] label
- [x] field width
- [x] name
- [x] value
- [x] input type
- [x] placeholder
- [x] tracking code
- [x] is disabled
- [x] is required
- [x] is readonly
- [x] is email
- [x] is url
- [x] style
- [x] validation pattern
- [x] validation max number
- [x] validation min number
- [x] validation step number
- [x] is selected
- [x] is multiple
- [x] accept file type
- [x] file min size
- [x] file max size
- [x] help
- [x] before content text
- [x] after content text
- [x] select form

# Block:
- [x] forms
- [x] form selector
- [x] checkboxes
- [x] checkbox
- [x] custom data
- [x] file
- [x] input
- [x] radios
- [x] radio
- [x] select
- [x] select-option
- [x] sender-email
- [x] submit
- [x] textarea

# Forms:
- [x] custom form
- [x] mailchimp
- [x] greenhouse
- [x] goodbits
- [x] mailerlite
- [x] hubspot

**Comment by goranalkovic-infinum** [comment]
Icons were added in Frontend libs:
https://github.com/infinum/eightshift-frontend-libs/pull/502
