### ISSUE TITLE
[BUG] Can't disable Custom select on frontend

### ISSUE THREAD

**Issue by goranalkovic-infinum** [infinum/eightshift-forms#186]
After disabling _Custom select_ on frontend in Global options, it still loads and makes everything look weird.

![image](https://user-images.githubusercontent.com/77000136/143246291-93e5725b-999a-4fd3-a9f8-a24ba6d0042a.png)

![image](https://user-images.githubusercontent.com/77000136/143246257-f68a06e0-8d60-4bb0-9432-e91696356aba.png)

**Comment by iruzevic** [comment]
this is fixed
