### ISSUE TITLE
Add licence for Geolocation

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-forms#232]
### Describe your feature request

We must provide geolocation link for the licence https://dev.maxmind.com/geoip/geolite2-free-geolocation-data?lang=en#license

and we should switch from db to web service

### Describe the solution you'd like

- [ ] provide a link to licence
- [ ] switch to web service

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by mbmjertan** [comment]
> and we should switch from db to web service

Why? There are privacy considerations to have about that.

**Comment by goranalkovic-infinum** [comment]
Besides privacy considerations, we would very quickly break through API limits, especially if there's a free tier.

Also, from their website:
> We highly recommend using a [server-side integration](https://dev.maxmind.com/geoip/geolocate-an-ip/web-services?lang=en), as it is more secure and more robust than a client-side integration.

😄
