### ISSUE TITLE
Scroll to on error - reverse logic

### ISSUE THREAD

**Issue by volfkarlo** [infinum/eightshift-forms#238]
### Describe your bug

In settings, if scroll to field on error is enabled nothing is happening.
We are looking for bug on `formDisableScrollToFieldOnError`
It appears in 6 positions.

<img width="662" alt="Screenshot 2022-06-21 at 11 50 00" src="https://user-images.githubusercontent.com/46056662/174771268-3857b200-db3a-4b5b-89e6-840d9ae3a546.png">

I believe it's about the condition in JS because it works if option it is checked in settings.

### Steps to Reproduce

1. Uncheck the `disable scroll to the first field on error`
<img width="581" alt="uncheck" src="https://user-images.githubusercontent.com/46056662/174771776-077acc18-16dc-491b-97e7-634d91c893bf.png">
2. Try to fill out any form with unfilled required fields.
3. Nothing happens

### Expected behavior

It should scroll to the first error if it appears.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
done
