### ISSUE TITLE
Init function on SPA like websites

### ISSUE THREAD

**Issue by volfkarlo** [infinum/eightshift-forms#239]
### Describe your bug

When using SPA lib like barba.js, if the first page that is open doesn't have a form, the form init function will not be exposed, because it is hooked to `domReady` function and the condition for initialization says it has to have a form to initialize.

The problem is the condition that checks the elements length
https://github.com/infinum/eightshift-forms/blob/406704a007e67b016cb4d4295ff8a092c01f8c72/src/Blocks/components/form/assets/index.js#L20

It should be still find if no element occurs.

### Steps to Reproduce

1. Make 2 pages, one with and one without the form on a project with Barba.js
2. Open the page without the form
3. Let Barba.js guide you to the page without the form(click on some link)
4. Try to fill out the form

### Expected behavior

Expected that everything works when no form is on the initial page.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/46056662/175236708-807967a0-5050-4f5b-8d75-5c66d081ca7e.mov

https://user-images.githubusercontent.com/46056662/175236821-6e6d8a31-6d32-4412-aa71-97363124ea5f.mov

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
done
