### ISSUE TITLE
Geolocation options behind the modal

### ISSUE THREAD

**Issue by volfkarlo** [infinum/eightshift-forms#241]
### Describe your bug

When setting geolocation to the form in the geolocation modal, form options appear behind the modal. Potentially just updating the EFElibs could fix this.

### Steps to Reproduce

1. Set the form to the page
2. Add the geolocation rule to the form
3. Click on the select field in geolocation forms

### Expected behavior

Should appear in front instead of behind the modal.

### Screenshots, screen recording, code snippet

<img width="715" alt="options behind the modal" src="https://user-images.githubusercontent.com/46056662/177559578-2dadf946-ed2e-4e44-a572-fa4ff68fb49d.png">

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
this is fixed
