### ISSUE TITLE
Simplify the code

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-forms#255]
Was checking out how to see if I have inner blocks, so I stumbled upon the code here

https://github.com/infinum/eightshift-forms/blob/46c5cf8fd43d1c1c4de120d7196388d4d8be415d/src/Blocks/custom/form-selector/components/form-selector-editor.js#L26-L35

and my editor suggested a simplification of this part to:

```jsx
	// Check if form selector has inner blocks.
	const hasInnerBlocksCheck = useSelect((select) => {
		const { innerBlocks } = select('core/block-editor').getBlock(clientId);

		return innerBlocks.length;
	});
```

**Comment by iruzevic** [comment]
tnx added, it will be on the next PR
