### ISSUE TITLE
Mailchimp form when submitting the existing email

### ISSUE THREAD

**Issue by gabriel-glo** [infinum/eightshift-forms#272]
### Describe your bug

When using Mailchimp integration form and entering the same email as one previously added, we are still getting the same generic success message.
Maybe research what API route is used and if we can somehow check if mail is already in the list.

### Steps to Reproduce

1. Set up Mailchimp form
2. Submit the form and add one email to the list
3. Submit the form again with the same email.

### Expected behavior

Get a message that says something like: `Email already in the list`

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
this is fixed
