### ISSUE TITLE
Active integration listing

### ISSUE THREAD

**Issue by volfkarlo** [infinum/eightshift-forms#275]
### Describe your feature request

We could separate the integrations on the form settings where there are active and inactive integrations or just show active integrations.

### Describe the solution you'd like

It would be awesome if or if possible to dictate the active integrations via the content from Gutenberg(read which form appears in the editor and then show it in the side bar)

This is the current situation
<img width="1618" alt="what we have" src="https://user-images.githubusercontent.com/46056662/200839968-8cd80223-9f5b-4270-bef5-d3e16f23e90b.png">

This would be a good solution.
<img width="1790" alt="also good solution" src="https://user-images.githubusercontent.com/46056662/200841053-518b64fd-cd54-4b54-8373-a7df7e8c2939.png">

And this would be the ideal situation.
<img width="1631" alt="how it would idealy look like" src="https://user-images.githubusercontent.com/46056662/200839943-8085b70a-b736-4820-bcd9-58279dd08a71.png">

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by mbmjertan** [comment]
Voting for the "good solution" as it makes enabling new integrations easier. I would prefer to have the label "available" for integrations that aren't used, but can be enabled, and the label "in use" for integrations that are used on the particular form.
