### ISSUE TITLE
Get select field placeholder from Hubspot integration

### ISSUE THREAD

**Issue by dadadavorin** [infinum/eightshift-forms#290]
### Describe your feature request

When adding Hubspot form the placeholder for Select field dropdown is not pulled from the Hubspot.

For example, we have placeholder "Company type" for the select field on the Hubspot, but on the website there is only default "Select opion" placeholder for select dropdown and it is not possible to change it. 

### Describe the solution you'd like

I would like that placeholder for select dropdown is also pulled from Hubspot like other fields.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
implemented in the latest beta release
