### ISSUE TITLE
Upload progress for files for dropzone library

### ISSUE THREAD

**Issue by volfkarlo** [infinum/eightshift-forms#297]
### Describe your feature request

There is a possibility that upload progress is handled by DropZone library itself. 

### Describe the solution you'd like

This is the approximate solution
https://stackoverflow.com/questions/38620641/how-to-show-upload-progress-percentage-in-dropzone-js

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
tnx this will be implemented as a part of the #298 issue.
