### ISSUE TITLE
Post query contains -1

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-forms#30]
https://github.com/infinum/eightshift-forms/blob/4db7b1dde059a80ca47cce7e3f8fa580e820d29c/src/blocks/components/post-select/components/post-select-options.js#L18-L23

This should be variable, not set to -1 (ever).

**Comment by IvanGrginovInf** [comment]
In JS this doesn't work the same as in PHP. You can put a number larger than 100 here (otherwise I believe validation will fail) BUT we need to get all so the only option is to put `-1`.

**Comment by dingo-d** [comment]
You can only put a number up to 100. Still, this is not ideal. As it queries all the posts in the database, right?
I assume this is used only for fetching form posts.

Even putting 100, instead of -1 is better as you are not fetching all the posts, and what's the chance that someone will have over 100 contact forms?

**Comment by IvanGrginovInf** [comment]
@dingo-d  Well this is not something I want to risk. Also -1 in this context means it will just ping the API route X times, fetching 100 posts each time. So if you hage 250 forms, it will ping the route 3 times.
