### ISSUE TITLE
[BUG] - Be aware of pluggable functions

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-forms#308]
In the `Helper` class you are using the `wp_salt()` function

https://github.com/infinum/eightshift-forms/blob/ccc582ca38453e2c3dcd7138e5b96e3b43db9e1b/src/Helpers/Helper.php#L44-L45

which is a pluggable function, and is loaded after the plugin is loaded.
I'm not sure why this works (could be due to the setup and the way things are autoloaded, or maybe because this is a static method, so late static binding applies).
A similar thing is used in the sso plugin, and because this function is a pluggable function, it's defined after the plugins are loaded.

https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-settings.php#L448-L468

So, if the function is used in a plugin there is a chance you'll get a function not defined error (happened to me when I wanted to implement a similar thing in my plugin).

Just a thing to keep in mind and check.

I solved this by just copying/pasting the same thing in my plugin from the `pluggable.php` (with proper attribution ofc).

**Comment by iruzevic** [comment]
Thank you for your valuable input, as always. I'm not entirely sure how this works, but it shouldn't be a problem to replace this part with another function. I'll go ahead and implement the changes. Thank you!

**Comment by iruzevic** [comment]
as this hasn't prove any issue so far I will close it
