### ISSUE TITLE
Workable forms failing because of textarea field being limited to 128 characters

### ISSUE THREAD

**Issue by dadadavorin** [infinum/eightshift-forms#311]
### Describe your bug

When user applies for a job on our website the Workable form is failing if user enters more than 128 characters in textarea field.

Errors returned:

Data got from integration response:

{"code":422,"message":"Unprocessable Entity"}
Data got from integration response body:

{"error":"Validation failed: Custom attribute values body is too long (maximum is 128 characters)","validation_errors":{"custom_attribute_values.body":["is too long (maximum is 128 characters)"]}}

### Steps to Reproduce

1. Go to [our client] webiste on a Careers page and choose some job you would like to apply to
2. Fill the form and enter more than 128 characters in the "Summary" textarea field
3. Form will fail with the errors explained above.

### Expected behavior

Chracter limit should be 2000 characters (based on previous fails) and field should not be validated on the frontend if characters exceed this limit.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
this is fixed in the latest beta release
