### ISSUE TITLE
[BUG] - "esForms-country" cookie not being set locally if WP Rocket plugin is not installed and activated

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-forms#316]
function [setEightshiftFormsLocationCookie()](https://github.com/infinum/eightshift-forms/blob/c64a53d0e21529eadfa91fc8761cc6ff778eff14/src/Geolocation/geolocationDetect.php#L18) bails out if `ES_GEOLOCATION_USE_WP_ROCKET_ADVANCED_CACHE` is not defined / WP Rocket plugin not installed and activated.

This prevents the geolocation cookie from being set and therefore cannot test locally

**Comment by iruzevic** [comment]
This is fixed, I have added a notice
