### ISSUE TITLE
[BUG] - "eightshift-forms/form-selector" block

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-forms#346]
I just install latest version but got....error when i want to create form

Your site doesn’t include support for the "eightshift-forms/form-selector" block. You can leave this block intact or remove it entirely.

Uncaught TypeError: Cannot read properties of undefined (reading 'kebabCase')
    at applicationBlocksEditor-f01fe7bd5d1f58baa41b.js?ver=4.0.107:1:1277903
    at Array.filter (<anonymous>)
    at x (applicationBlocksEditor-f01fe7bd5d1f58baa41b.js?ver=4.0.107:1:1277871)
    at C (applicationBlocksEditor-f01fe7bd5d1f58baa41b.js?ver=4.0.107:1:1278620)
    at M (applicationBlocksEditor-f01fe7bd5d1f58baa41b.js?ver=4.0.107:1:1279189)
    at applicationBlocksEditor-f01fe7bd5d1f58baa41b.js?ver=4.0.107:1:1280839
    at Array.map (<anonymous>)
    at applicationBlocksEditor-f01fe7bd5d1f58baa41b.js?ver=4.0.107:1:1280461
    at applicationBlocksEditor-f01fe7bd5d1f58baa41b.js?ver=4.0.107:1:1281639
    at applicationBlocksEditor-f01fe7bd5d1f58baa41b.js?ver=4.0.107:1:1281869

**Comment by iruzevic** [comment]
What is your exact version of the plugin?

**Comment by marijang** [comment]
4.0.107

**Comment by marijang** [comment]
hm i check on clean theme ... i didn't remove anything from files

**Comment by marijang** [comment]
where i can check this?

**Comment by iruzevic** [comment]
Do you installed the plugin from the release or you downloaded the GitHub repo?

https://github.com/infinum/eightshift-forms/releases/tag/4.0.107-alpha

Release.zip

**Comment by marijang** [comment]
Yes

**Comment by iruzevic** [comment]
Could you activate the stock twentysomething theme and see if the error is still there

**Comment by marijang** [comment]
the same error i get

**Comment by marijang** [comment]
<img width="942" alt="Screen Shot 2023-12-02 at 16 08 04" src="https://github.com/infinum/eightshift-forms/assets/1381443/e62551ac-dbae-4cc6-9b7e-74517d4de903">

**Comment by marijang** [comment]
also i have other questions....
1. I want to create plugin for woocommerce i use your plugin but i don7t know how to add blocks and components....
2. i want to use in plugin already defined blocks / components like heading, paragraphm buttons etc..... is it possible?

**Comment by marijang** [comment]
wordpress verision is 6.4

**Comment by marijang** [comment]
I create new instace of wordpress and i get the same error...

**Comment by iruzevic** [comment]
I have tested the latest forms with the stock twenty theme and it is working. The issue can occur on the php8+ versions as forms are still not supporting it. We will make a release by the end of the week

**Comment by iruzevic** [comment]
The issue was with the latest WP version 6.4+ because they removed loadash from default scripts. Please install from s version 109 and it will work.

https://github.com/infinum/eightshift-forms/releases/tag/4.0.109-alpha

**Comment by marijang** [comment]
Great. Can you add woocommerce support / bugfix which is fixed in theme
