### ISSUE TITLE
[BUG] - Forms not working on PHP 8.2

### ISSUE THREAD

**Issue by iobrado** [infinum/eightshift-forms#353]
- Local environment: **Laravel Herd 1.3.1**
- **PHP 8.2.13**
- **WP 6.4.2** (latest version at the time of submitting this issue)
- **Eightshift Forms 4.0.116**
- ES Frontend Libs 9.1.0
- ES Libs 7.1.0

When doing a clean install of the Eightshift theme and installing the latest version of Eightshift Forms, I'm getting the following errors:

On the frontend, at the bottom of the page:

`Fatal error: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /Users/.../Sites/eightshift/wp-content/plugins/eightshift-forms/src/Helpers/Helper.php:855 Stack trace: #0 /Users/.../Sites/eightshift/wp-content/plugins/eightshift-forms/src/Helpers/Helper.php(855): method_exists(NULL, 'is_block_editor') #1 /Users/.../Sites/eightshift/wp-content/plugins/eightshift-forms/src/AdminMenus/FormAdminBarMenu.php(74): EightshiftForms\Helpers\Helper::isBlockEditor() #2 /Users/.../Sites/eightshift/wp-includes/class-wp-hook.php(324): EightshiftForms\AdminMenus\FormAdminBarMenu->getTopBarMenu(Object(WP_Admin_Bar)) #3 /Users/.../Sites/eightshift/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #4 /Users/.../Sites/eightshift/wp-includes/plugin.php(565): WP_Hook->do_action(Array) #5 /Users/.../Sites/eightshift/wp-includes/admin-bar.php(95): do_action_ref_array('admin_bar_menu', Array) #6 /Users/.../Sites/eightshift/wp-includes/class-wp-hook.php(324): wp_admin_bar_render('') #7 /Users/.../Sites/eightshift/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #8 /Users/.../Sites/eightshift/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #9 /Users/.../Sites/eightshift/wp-includes/general-template.php(3068): do_action('wp_footer') #10 /Users/.../Sites/eightshift/wp-content/themes/devkit/footer.php(19): wp_footer() #11 /Users/.../Sites/eightshift/wp-includes/template.php(790): require_once('/Users/...') #12 /Users/.../Sites/eightshift/wp-includes/template.php(725): load_template('/Users/...', true, Array) #13 /Users/.../Sites/eightshift/wp-includes/general-template.php(92): locate_template(Array, true, true, Array) #14 /Users/.../Sites/eightshift/wp-content/themes/devkit/index.php(19): get_footer() #15 /Users/.../Sites/eightshift/wp-includes/template-loader.php(106): include('/Users/...') #16 /Users/.../Sites/eightshift/wp-blog-header.php(19): require_once('/Users/...') #17 /Users/.../Sites/eightshift/index.php(17): require('/Users/...') #18 /Applications/Herd.app/Contents/Resources/valet/server.php(120): require('/Users/...') #19 {main} thrown in /Users/.../Sites/eightshift/wp-content/plugins/eightshift-forms/src/Helpers/Helper.php on line 855`

In the Forms editor, when adding a new basic contact form
![Screenshot 2023-12-20 at 09 13 35](https://github.com/infinum/eightshift-forms/assets/23059501/533359f8-ab48-4248-9ca5-b06b5066f133)

![Screenshot 2023-12-20 at 09 14 01](https://github.com/infinum/eightshift-forms/assets/23059501/22fa3d56-ca75-4bed-a060-e98f8c659e98)

**Comment by iruzevic** [comment]
Fixed, the issue was that method_exists will throw a fatal error if object\string is not passed. Before it only silently failed
