### ISSUE TITLE
Feature - is it possible to have different select options based on previously selected option?

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-forms#38]
One of the requirements I'll have in a client's project is to have a radio field with some options and based on the selected radio option the select dropdown below would have different options chosen. Like a linked options type of thing.

Is this currently possible to do and what would we have to do in order to get that working?

**Comment by IvanGrginovInf** [comment]
@dingo-d This feature isn't currently supported (dynamic field based on other fields) out of the box yet. 

However you have 2 options:
- You can implement this in your project in JS. (onChange radio -> select different `<select>` option).
- You can implement your own block(s) which do this, allow it in Forms CPT and you're good to go (see filter `eightshift_forms/allowed_blocks`): https://github.com/infinum/eightshift-forms/blob/develop/src/hooks/class-filters.php#L103)

**Comment by iruzevic** [comment]
We hava a new ticket for this on a new form
