### ISSUE TITLE
[BUG] - Hubspot UTK cookie blocking the user from submitting the form

### ISSUE THREAD

**Issue by dadadavorin** [infinum/eightshift-forms#423]
When user tries to submit the form it is getting the error in the screenshot related to the Hubspot UTK cookie:

![image](https://github.com/infinum/eightshift-forms/assets/81157133/612b8889-227b-4030-b749-d46d18c71091)

More info on Hubspot cookies on the [link](https://knowledge.hubspot.com/privacy-and-consent/what-cookies-does-hubspot-set-in-a-visitor-s-browser#functionality-cookies).

I have not been able to reproduce this while testing.

**Comment by iruzevic** [comment]
fixed
