### ISSUE TITLE
[BUG] - Number field accepts text in Safari and Firefox

### ISSUE THREAD

**Issue by iobrado** [infinum/eightshift-forms#425]
- MacOS Sonoma 14.4.1
- Safari 17.4.1, Firefox 126.0.1
- tested on a clean install of Eightshift theme and Eightshift Forms `3.1.12`

When using Safari or Firefox, the number field in Eightshift Forms allows text as well. If a form is submitted with text in the number field, the form will be sent successfully, but the value entered in the number field won't be displayed in an e-mail.

When testing in Chrome and Edge, the only letter that can be entered in the number field is a single `e`. This is not necessarily a bug, but I'm just pointing it out.

### Chrome Screenshot
<img width="884" alt="Screenshot 2024-06-03 at 16 11 16" src="https://github.com/infinum/eightshift-forms/assets/23059501/3a82c044-6fd6-4f75-a39d-58fc765a0be9">

### Safari Video example

https://github.com/infinum/eightshift-forms/assets/23059501/787e56c6-b5ab-41d0-a745-1e7dd5fbfb20

**Comment by iruzevic** [comment]
fixed
