### ISSUE TITLE
[FEATURE] - Tailwind styling?

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-forms#459]
Do you have in plan to introduce tailwind styles to the forms? Or an easy way to implement them, alongside the existing classes?

Some switch in the options that would allow the users to apply custom tailwind styles to the forms ootb?

CC @goranalkovic-infinum

**Comment by iruzevic** [comment]
Already done here are the hooks

https://github.com/infinum/eightshift-docs/issues/252

Select (choices) can't be styled this way but there is a workaround. Ask @mbmjertan for examples i have sent it to him

**Comment by dingo-d** [comment]
Nice! Thanks 👍🏼
