### ISSUE TITLE
[BUG] - Faulty TalentLyft help instructions

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-forms#473]
The links are wrong here:
<img width="594" alt="image" src="https://github.com/user-attachments/assets/8f60cc74-d702-4a87-ab4f-cb803205e2b0" />

Should be something along the lines of:

1. You'll need to first create an account: https://accounts.talentlyft.com/register
2. Access the account and go to Settings > integrations
3. Click on Settings under the TalentLyft card. 
4. Generate a new API token. 
5. Copy the API key into the field under the General here tab or use the global PHP constant.

**Comment by iruzevic** [comment]
Well, it should be obvious that you need to have an account on Talentlyft before creating an API. I don't want to go into that extreme "dummification" of instructions.
