### ISSUE TITLE
When Eightshift Forms plugin is active Eightshift theme blocks are not visible.

### ISSUE THREAD

**Issue by JerrySpecter** [infinum/eightshift-forms#61]
When I clone and install Eightshift forms plugin inside my plugins folder, and activate it, the plugin is working correctly but then i can't use any of the custom blocks from eightshift boilerplate theme.

Running latest versions of the plugin and boilerplate.

What are the steps to correctly install, activate and use the plugin with the boilerplate?

**Comment by IvanGrginovInf** [comment]
@JerrySpecter Haven't tested the forms with the current stable boilerplate theme version (it most likely won't work correctly). This plugin is still under heavy development, there's no real documentation at the time of writing this (working on it!) so I wouldn't really recommend you use it in a production setup (just yet).

That being said, if you really need this right now, and you install the bleeding edge boilerplate using `npx create-wp-project --eightshiftLibsBranch="release/3.1.0" --eightshiftFrontendLibsBranch="develop"` AND you install the latest version of forms + integrate these changes https://github.com/infinum/eightshift-forms/pull/60 it **_should_** work. (but as you can see, it's not really stable at the moment).

**Comment by JerrySpecter** [comment]
@IvanGrginovInf  Thanks for the info. I'll wait for the stable release :)
