### ISSUE TITLE
[NEW FORMS] Greenhouse attachments fields

### ISSUE THREAD

**Issue by goranalkovic-infinum** [infinum/eightshift-forms#73]
It would be nice if with Greenhouse attachment fields would have options to either:
- leave only the file upload part and hide the text URL input
- leave only the text URL input and hide the file upload part
- have both visible, but either have a toggle to switch to text or just have a different label on the URL field (something like _...or provide a link to your file (for example on Google Drive, Dropbox, etc.)_

**Comment by iruzevic** [comment]
added via settings
