### ISSUE TITLE
[NEW FORMS] Basic blocks and allowing certain theme blocks

### ISSUE THREAD

**Issue by goranalkovic-infinum** [infinum/eightshift-forms#74]
It would be nice if we had a couple of basic blocks available, like _Paragraph_ and _Heading_ because sometimes our forms need those to disclose certain things, link to privacy policies, etc.

Also, maybe in the future it would be nice if we had a filter that would allow us in our theme to allow some of the theme blocks to be used inside Forms.

**Comment by iruzevic** [comment]
added via filter
